# Generated by Django 5.2 on 2025-04-21 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wants_electroplating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='wants_engraving',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('finish_type', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='customizations/')),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.design')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='tracker.order')),
            ],
        ),
    ]
